# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A MYSQL
# ===================================================================
# Reemplazá 'localhost:3306' si tu MySQL está en otra IP o puerto de la planta
spring.datasource.url=jdbc:mysql://localhost:3306/agropoly_recuperado?createDatabaseIfNotExist=true&serverTimezone=UTC

# Poné acá tu usuario y contraseña real de tu MySQL
spring.datasource.username=root
spring.datasource.password=yessa.218

# Driver oficial de MySQL (el que acabamos de meter en el pom.xml)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA (El mapa automático de tablas)
# ===================================================================
# Dialecto específico para que Spring hable el idioma nativo de MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ddl-auto=update: Revisa tu código Java y, si agregás campos, crea o modifica 
# las tablas en MySQL automáticamente sin borrar los datos existentes. ¡Ultra seguro!
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de la computadora cada comando SQL que se ejecuta (ideal para auditoría)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true